// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuikPic.Web;

#nullable disable

namespace QuikPic.Web.Migrations
{
    [DbContext(typeof(QuikPicContext))]
    partial class QuikPicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("QuikPic.Web.Models.Preset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Brightness")
                        .HasColumnType("REAL");

                    b.Property<float>("Contrast")
                        .HasColumnType("REAL");

                    b.Property<float>("Grain")
                        .HasColumnType("REAL");

                    b.Property<float>("Grayscale")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Saturation")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<float>("Tint")
                        .HasColumnType("REAL");

                    b.Property<float>("Vignette")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Presets");
                });
#pragma warning restore 612, 618
        }
    }
}
